# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad8f1fb31acce21b55ff6025324aaa6f1105c202a152a47b0c4b47bf3c23b17cbd4c92483f09c7869ba9c13b77d448a1ffa10cca12c54d33ae4325d5273cf34

test:
  secret_key_base: 4514056c7edef10c9420421df3c42dbcb8c16f02aa64abded963c8bd80e5e4099038e0a15b7d27aee834b24736bbe6add6359d714de15ccefe15fdb0155c0e52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
